import React from 'react';

export default function ConnectionInfo({ t, mobile }) {
  return <div className="mt-4 space-y-3 text-xs leading-5 text-zinc-500">
    <p>{mobile ? t('На телефоне отображается сохранённая история. «Не подключён» означает, что на этом устройстве нет помощника MT5 — подключение на ПК от этого не отключается. Войдите в тот же аккаунт DAYRIS; если новые сделки ещё не видны, обновите календарь после синхронизации на ПК.', 'Your phone shows saved history. “Not connected” means this device has no MT5 companion; it does not disconnect your PC. Use the same DAYRIS account and refresh the calendar after syncing on your PC if needed.', 'Telefonul afișează istoricul salvat. „Neconectat” înseamnă că acest dispozitiv nu are asistent MT5; conexiunea de pe PC rămâne activă. Folosește același cont DAYRIS și actualizează calendarul după sincronizarea pe PC.') : t('История проверяется при подключении, по кнопке «Синхронизировать» и каждые 30 секунд при включённой автосинхронизации. MT5, помощник и календарь должны оставаться открыты на этом ПК. Окно подключения можно закрыть, помощник — свернуть.', 'History is checked on connection, when you press Synchronize, and every 30 seconds with auto-sync enabled. Keep MT5, the companion and calendar open on this PC. You can close this dialog and minimize the companion.', 'Istoricul este verificat la conectare, la apăsarea Sincronizează și la fiecare 30 de secunde cu sincronizarea automată activată. Menține MT5, asistentul și calendarul deschise pe PC. Poți închide acest dialog și minimiza asistentul.')}</p>
    <details>
      <summary className="cursor-pointer font-semibold">{t('Какие данные читает DAYRIS?', 'What does DAYRIS read?', 'Ce date citește DAYRIS?')}</summary>
      <div className="mt-2 space-y-2">
        <p>{t('В календарь передаются полностью закрытые позиции: инструмент, направление, дата и время, результат, комиссии и своп. Для выбора счёта читаются его номер, брокер, сервер, тип Demo/Live, баланс и валюта. Открытые позиции проверяются, чтобы не импортировать незавершённые сделки.', 'The calendar receives fully closed positions: instrument, direction, date and time, result, commissions and swap. Account selection uses the account number, broker, server, Demo/Live type, balance and currency. Open positions are checked to exclude unfinished trades.', 'Calendarul primește poziții complet închise: instrument, direcție, dată și oră, rezultat, comisioane și swap. Pentru selectarea contului sunt citite numărul, brokerul, serverul, tipul Demo/Live, soldul și moneda. Pozițiile deschise sunt verificate pentru a exclude tranzacțiile neîncheiate.')}</p>
        <p>{t('Помощник не запрашивает и не передаёт пароль брокера, не открывает и не закрывает сделки. Он общается с DAYRIS только на вашем компьютере. Сохранённые сделки загружаются в ваш аккаунт DAYRIS, чтобы календарь был доступен на телефоне. «Отключить» прекращает доступ помощника; сохранённая история остаётся.', 'The companion neither requests nor transmits your broker password and does not open or close trades. It communicates with DAYRIS on your computer. Saved trades are uploaded to your DAYRIS account for access on your phone. Disconnect revokes companion access; saved history remains.', 'Asistentul nu solicită și nu transmite parola brokerului și nu deschide sau închide tranzacții. Comunică cu DAYRIS pe calculatorul tău. Tranzacțiile salvate sunt încărcate în contul DAYRIS pentru acces pe telefon. Deconectarea revocă accesul asistentului; istoricul salvat rămâne.')}</p>
      </div>
    </details>
  </div>;
}
