import React from 'react';

export default function ConnectionInfo({ t, mobile }) {
  return <div className="mt-4 space-y-3 text-xs leading-5 text-zinc-500">
    <p>{mobile ? t('На телефоне отображается сохранённая история. «Не подключён» означает, что на этом устройстве нет помощника MT5 — подключение на ПК от этого не отключается. Войдите в тот же аккаунт DAYRIS; если новые сделки ещё не видны, обновите календарь после синхронизации на ПК.', 'Your phone shows saved history. “Not connected” means this device has no MT5 companion; it does not disconnect your PC. Use the same DAYRIS account and refresh the calendar after syncing on your PC if needed.', 'Telefonul afișează istoricul salvat. „Neconectat” înseamnă că acest dispozitiv nu are asistent MT5; conexiunea de pe PC rămâne activă. Folosește același cont DAYRIS și actualizează calendarul după sincronizarea pe PC.', "手机显示已保存历史。“未连接”表示此设备没有 MT5 助手，不会断开电脑连接。使用相同 DAYRIS 账户，必要时在电脑同步后刷新手机日历。") : t('История проверяется при подключении, по кнопке «Синхронизировать» и каждые 30 секунд при включённой автосинхронизации. MT5, помощник и календарь должны оставаться открыты на этом ПК. Окно подключения можно закрыть, помощник — свернуть.', 'History is checked on connection, when you press Synchronize, and every 30 seconds with auto-sync enabled. Keep MT5, the companion and calendar open on this PC. You can close this dialog and minimize the companion.', 'Istoricul este verificat la conectare, la apăsarea Sincronizează și la fiecare 30 de secunde cu sincronizarea automată activată. Menține MT5, asistentul și calendarul deschise pe PC. Poți închide acest dialog și minimiza asistentul.', "连接时、点击同步时，以及开启自动同步后每 30 秒检查历史。请在此电脑上保持 MT5、助手和日历打开。可以关闭此窗口并最小化助手。")}</p>
    <details>
      <summary className="cursor-pointer font-semibold">{t('Какие данные читает DAYRIS?', 'What does DAYRIS read?', 'Ce date citește DAYRIS?', "DAYRIS 读取哪些数据？")}</summary>
      <div className="mt-2 space-y-2">
        <p>{t('В календарь передаются полностью закрытые позиции: инструмент, направление, дата и время, результат, комиссии и своп. Для выбора счёта читаются его номер, брокер, сервер, тип Demo/Live, баланс и валюта. Открытые позиции проверяются, чтобы не импортировать незавершённые сделки.', 'The calendar receives fully closed positions: instrument, direction, date and time, result, commissions and swap. Account selection uses the account number, broker, server, Demo/Live type, balance and currency. Open positions are checked to exclude unfinished trades.', 'Calendarul primește poziții complet închise: instrument, direcție, dată și oră, rezultat, comisioane și swap. Pentru selectarea contului sunt citite numărul, brokerul, serverul, tipul Demo/Live, soldul și moneda. Pozițiile deschise sunt verificate pentru a exclude tranzacțiile neîncheiate.', "日历接收完全平仓头寸的品种、方向、日期时间、结果、佣金和隔夜利息。选择账户时读取账号、经纪商、服务器、模拟/真实类型、余额和货币。检查未平仓头寸以排除未完成交易。")}</p>
        <p>{t('Помощник не запрашивает и не передаёт пароль брокера, не открывает и не закрывает сделки. Он общается с DAYRIS только на вашем компьютере. Сохранённые сделки загружаются в ваш аккаунт DAYRIS, чтобы календарь был доступен на телефоне. «Отключить» прекращает доступ помощника; сохранённая история остаётся.', 'The companion neither requests nor transmits your broker password and does not open or close trades. It communicates with DAYRIS on your computer. Saved trades are uploaded to your DAYRIS account for access on your phone. Disconnect revokes companion access; saved history remains.', 'Asistentul nu solicită și nu transmite parola brokerului și nu deschide sau închide tranzacții. Comunică cu DAYRIS pe calculatorul tău. Tranzacțiile salvate sunt încărcate în contul DAYRIS pentru acces pe telefon. Deconectarea revocă accesul asistentului; istoricul salvat rămâne.', "助手不会请求或传输经纪商密码，也不会开仓或平仓。它在电脑上与 DAYRIS 通信。保存的交易上传到 DAYRIS 账户，供手机查看。断开连接会撤销助手访问，已保存历史仍保留。")}</p>
      </div>
    </details>
  </div>;
}
