import {spokenText} from '../lib/spokenText.js';
import React,{useEffect,useRef,useState} from 'react';
import {voicesForLocale,selectPlaybackVoice} from '../lib/voicePlayback.js';
export default function VoiceSettings({language,isLight}){
 const locale=language==='en'?'en':['md','ro'].includes(language)?'ro':'ru';
 const copy={ru:{title:'Голос помощника',auto:'Автоматически',preview:'Послушать',sample:'Привет! Я помогу вести календарь и разбираться в ваших финансах.',note:'Язык команд совпадает с языком приложения.',missing:'Русский голос недоступен. На Android проверьте «Синтез речи» в настройках устройства и установите русский язык.',error:'Не удалось включить звук. Проверьте громкость и доступные голоса.'},en:{title:'Assistant voice',auto:'Automatic',preview:'Preview',sample:'Hello! I can help you track your calendar and finances.',note:'Voice commands use the app language.',missing:'No English voice is installed on this device.',error:'Audio could not start. Check the volume and available voices.'},ro:{title:'Vocea asistentului',auto:'Automat',preview:'Ascultă',sample:'Salut! Te ajut să gestionezi calendarul și finanțele tale.',note:'Comenzile vocale folosesc limba aplicației.',missing:'Nu există o voce română instalată pe dispozitiv.',error:'Sunetul nu a pornit. Verifică volumul și vocile disponibile.'}}[locale];
 const key=`dayris_voice:${locale}`,read=()=>{try{return localStorage.getItem(key)||'';}catch{return '';}};
 const [selected,setSelected]=useState(read),[voices,setVoices]=useState([]),[error,setError]=useState('');
 const speech=useRef(null),timer=useRef(null);
 function stop(){clearTimeout(timer.current);if(speech.current){speech.current.onstart=speech.current.onend=speech.current.onerror=null;speech.current=null;window.speechSynthesis?.cancel();}}
 useEffect(()=>{setSelected(read());setError('');stop();},[locale]);
 useEffect(()=>{const synth=window.speechSynthesis;if(!synth)return;const update=()=>setVoices(synth.getVoices());update();synth.addEventListener?.('voiceschanged',update);const hidden=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',hidden);return()=>{stop();synth.removeEventListener?.('voiceschanged',update);document.removeEventListener('visibilitychange',hidden);};},[]);
 const available=voicesForLocale(voices,locale);
 function preview(){stop();setError('');if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){setError(copy.missing);return;}const utterance=new SpeechSynthesisUtterance(spokenText(copy.sample,locale));speech.current=utterance;utterance.lang={ru:'ru-RU',en:'en-US',ro:'ro-RO'}[locale];utterance.rate=1;utterance.pitch=1;const voice=selectPlaybackVoice(window.speechSynthesis.getVoices(),locale,selected,navigator.onLine!==false);if(!voice){speech.current=null;setError(copy.missing);return;}utterance.voice=voice;utterance.onstart=()=>clearTimeout(timer.current);utterance.onend=()=>{if(speech.current===utterance){clearTimeout(timer.current);speech.current=null;}};utterance.onerror=()=>{if(speech.current===utterance){stop();setError(copy.error);}};timer.current=setTimeout(()=>{if(speech.current===utterance){stop();setError(copy.error);}},3500);try{window.speechSynthesis.resume();window.speechSynthesis.speak(utterance);}catch{stop();setError(copy.error);}}
 return <div className="mt-3" data-voice-settings><label className={`block text-[11px] mb-1.5 ${isLight?'text-zinc-500':'text-zinc-400'}`} htmlFor="assistant-voice">{copy.title}</label><div className="flex gap-1.5"><select id="assistant-voice" value={available.some(voice=>voice.voiceURI===selected)?selected:''} onChange={event=>{stop();setSelected(event.target.value);try{localStorage.setItem(key,event.target.value);}catch{/* Session preference is still usable. */}}} className={`min-w-0 flex-1 min-h-[44px] rounded-xl border px-2 text-xs ${isLight?'bg-white border-zinc-300 text-zinc-700':'bg-zinc-900 border-zinc-700 text-zinc-300'}`}><option value="">{copy.auto}</option>{available.map(voice=><option key={voice.voiceURI} value={voice.voiceURI}>{voice.name}</option>)}</select><button type="button" onClick={preview} className="min-h-[44px] rounded-xl border border-amber-400/30 px-3 text-xs text-amber-500">{copy.preview}</button></div><p className="mt-1.5 text-[10px] text-zinc-500">{copy.note}</p>{!available.length&&<p className="mt-1 text-[10px] text-zinc-500">{copy.missing}</p>}{error&&<p role="alert" className="mt-1 text-[11px] text-amber-500">{error}</p>}</div>;
}
