const copy = {
  zh: {
    title:'你的个人财务。',titleAccent:'完整的全貌。',intro:'独立钱包、个人储蓄计划和统一交易日志，让你更好地掌控资金。DAYRIS PRO 将记录变成下一步行动。',explore:'探索更多功能',example:'示例 · 非个人数据',wallet:'钱包',money:'储蓄计划',trader:'交易',walletTitle:'清楚掌握可用资金。',walletBody:'记录资金收入和支出。个人余额和历史使用独立账户，不影响交易盈亏。',walletPoints:['独立余额','专属收支历史','保存到账户'],balance:'钱包可用余额',received:'收入',spent:'支出',moneyTitle:'有意识地留下更多。',moneyBody:'免费版包含收入和支出概览。PRO 帮你发现重复支出和值得重新考虑的购买。选择要减少的支出，保存计划，并在遇到类似支出时获得温和提醒。',moneyPoints:['按记录分析支出','计算可能节省的资金','提醒你的选择'],savingsCaption:'如果该类别支出减少 15%',savingsResult:'同一时段可多保留的资金',expenses:'时段支出',categories:['购物','餐饮','交通'],traderTitle:'两个连接，一个交易日志。',traderBody:'开启交易模式，独立查看交易、盈亏、收益曲线及分析。通过各自菜单连接 cTrader 和 MetaTrader 5。',traderPoints:['交易日志和盈亏分析','各平台独立选择交易账户','独立同步与导入结果'],tradeResult:'交易结果',tradeDetail:'品种 · 方向 · 笔记',choose:'选择开启 PRO 的方式',inviteTitle:'邀请好友获得 26 天',inviteBody:'邀请好友，好友的第一条记录将为你解锁 26 天 PRO，为好友解锁 7 天。',inviteAction:'邀请好友',buyTitle:'直接开启，无需邀请',buyBody:'一个月的全部 PRO 功能。',renewBody:'继续使用全部 PRO 功能。',buyAction:'开启 PRO',renewAction:'续订 PRO',openWallet:'打开我的钱包',signalsTitle:'XAUUSD 自动信号',signalsBody:'Gold Scalping 提供 AI 市场分析、黄金（XAUUSD）自动信号和结果报告。Telegram 机器人发送信号，交易决策由你负责。',signalsBot:'可选连接 cTrader 自动交易机器人 Skalp_XAUUSD 使用同样的信号。终端安装和 VPS 托管需另行安排，说明及当前条件请查看频道。',signalsNote:'这是独立连接，DAYRIS 日志同步不会启动自动交易。信号不保证盈利，交易可能导致本金损失。',signalsAction:'频道和自动交易连接',signalsReceive:'通过 Telegram 机器人接收信号',ctraderGuide:'直接连接：选择账户并导入交易，菜单显示日志记录数量和最近新增结果。',mt5Guide:'通过免费 Windows 助手连接。自动更新需要在电脑上同时打开 MT5、助手和 Chrome/Edge 中的 DAYRIS。交易通过 DAYRIS 云同步到手机。',openPlatforms:'打开交易平台',
  },
  ru: {
    title: 'Личные деньги.', titleAccent: 'Полная картина.',
    intro: 'Больше контроля над деньгами: отдельный кошелёк, личный план экономии и единый журнал торговли. DAYRIS PRO превращает записи в следующие шаги.',
    explore: 'Посмотри, что откроется', example: 'Пример · не твои данные',
    wallet: 'Кошелёк', money: 'План экономии', trader: 'Трейдинг',
    walletTitle: 'Знай, сколько у тебя есть.',
    walletBody: 'Добавляй поступления и траты. Баланс и история личных денег живут на отдельном счёте и не меняют торговый PnL.',
    walletPoints: ['Отдельный баланс', 'Своя история операций', 'Сохранение в аккаунте'],
    balance: 'Доступно в кошельке', received: 'Добавлено', spent: 'Потрачено',
    moneyTitle: 'Оставляй больше. Осознанно.',
    moneyBody: 'Обзор доходов и расходов есть в FREE. PRO находит повторяющиеся траты и покупки, которые стоит пересмотреть. Выбирай, что сократить, сохраняй план и получай мягкие напоминания при похожих тратах.',
    moneyPoints: ['Разбор расходов по твоим записям', 'Расчёт возможной экономии', 'Напоминания о твоём выборе'],
    savingsCaption: 'Если сократить категорию на 15%', savingsResult: 'останется за тот же период',
    expenses: 'Расходы за период', categories: ['Покупки', 'Кафе', 'Транспорт'],
    traderTitle: 'Каждая сделка — с контекстом.',
    traderBody: 'Включай трейдера, когда нужен журнал сделок, PnL и аналитика. cTrader помогает синхронизировать сделки автоматически.',
    traderPoints: ['Журнал сделок', 'PnL и аналитика', 'Подключение cTrader'],
    tradeResult: 'Результат сделки', tradeDetail: 'Инструмент · направление · заметки',
    choose: 'Твой способ открыть PRO', inviteTitle: '26 дней за приглашение',
    inviteBody: 'Пригласи друга. Его первая запись откроет тебе 26 дней PRO. Другу — 7 дней.',
    inviteAction: 'Пригласить друга', buyTitle: 'Сразу, без приглашения',
    buyBody: 'Все возможности PRO на месяц.', renewBody: 'Продолжай пользоваться всеми возможностями PRO.',
    buyAction: 'Подключить PRO', renewAction: 'Продлить PRO', openWallet: 'Открыть мой кошелёк',
  },
  en: {
    title: 'Your personal money.', titleAccent: 'The complete picture.',
    intro: 'More control over your money: a separate wallet, a personal savings plan and one trading journal. DAYRIS PRO turns entries into next steps.',
    explore: 'Explore what you unlock', example: 'Example · not your data',
    wallet: 'Wallet', money: 'Savings plan', trader: 'Trading',
    walletTitle: 'Know what you have.',
    walletBody: 'Record money coming in and going out. Your personal balance and history have their own account and never change trading PnL.',
    walletPoints: ['Separate balance', 'Your own activity history', 'Saved to your account'],
    balance: 'Available in your wallet', received: 'Added', spent: 'Spent',
    moneyTitle: 'Keep more. With intention.',
    moneyBody: 'The income and spending overview is included in FREE. PRO finds repeat spending and purchases worth reviewing. Choose what to reduce, save your plan and get gentle reminders with similar expenses.',
    moneyPoints: ['Review spending from your entries', 'Calculate potential savings', 'Reminders of your choices'],
    savingsCaption: 'If you reduce the category by 15%', savingsResult: 'kept over the same period',
    expenses: 'Spending for the period', categories: ['Shopping', 'Cafés', 'Transport'],
    traderTitle: 'Every trade in context.',
    traderBody: 'Enable Trader when you need a trade journal, PnL and analytics. Connect cTrader to sync trades automatically.',
    traderPoints: ['Trade journal', 'PnL and analytics', 'cTrader connection'],
    tradeResult: 'Trade result', tradeDetail: 'Instrument · direction · notes',
    choose: 'Your way to unlock PRO', inviteTitle: '26 days for an invitation',
    inviteBody: 'Invite a friend. Their first entry unlocks 26 days of PRO for you and 7 days for them.',
    inviteAction: 'Invite a friend', buyTitle: 'Start without an invitation',
    buyBody: 'All PRO features for a month.', renewBody: 'Keep using every PRO feature.',
    buyAction: 'Get PRO', renewAction: 'Extend PRO', openWallet: 'Open my wallet',
  },
  ro: {
    title: 'Banii tăi personali.', titleAccent: 'Imaginea completă.',
    intro: 'Mai mult control: un portofel separat, un plan personal de economisire și un singur jurnal de trading. DAYRIS PRO transformă înregistrările în pași concreți.',
    explore: 'Descoperă ce primești', example: 'Exemplu · nu sunt datele tale',
    wallet: 'Portofel', money: 'Economisire', trader: 'Trading',
    walletTitle: 'Știi câți bani ai.',
    walletBody: 'Înregistrează încasări și cheltuieli. Soldul personal și istoricul au un cont separat și nu modifică PnL-ul din trading.',
    walletPoints: ['Sold separat', 'Istoric propriu', 'Salvat în contul tău'],
    balance: 'Disponibil în portofel', received: 'Adăugat', spent: 'Cheltuit',
    moneyTitle: 'Păstrează mai mult. Conștient.',
    moneyBody: 'Rezumatul veniturilor și cheltuielilor este inclus în FREE. PRO găsește cheltuieli repetate și cumpărături de revizuit. Alege ce reduci, salvează planul și primește sugestii la cheltuieli similare.',
    moneyPoints: ['Analiză din înregistrările tale', 'Calculul economiilor posibile', 'Sugestii despre alegerile tale'],
    savingsCaption: 'Dacă reduci categoria cu 15%', savingsResult: 'păstrați în aceeași perioadă',
    expenses: 'Cheltuieli în perioadă', categories: ['Cumpărături', 'Cafenele', 'Transport'],
    traderTitle: 'Fiecare tranzacție are context.',
    traderBody: 'Activează modul Trader pentru jurnal, PnL și analiză. Conectează cTrader pentru sincronizarea automată a tranzacțiilor.',
    traderPoints: ['Jurnal de tranzacții', 'PnL și analiză', 'Conectare cTrader'],
    tradeResult: 'Rezultatul tranzacției', tradeDetail: 'Instrument · direcție · notițe',
    choose: 'Cum vrei să activezi PRO', inviteTitle: '26 de zile pentru o invitație',
    inviteBody: 'Invită un prieten. Prima lui înregistrare îți oferă 26 de zile PRO, iar lui — 7 zile.',
    inviteAction: 'Invită un prieten', buyTitle: 'Începe fără invitație',
    buyBody: 'Toate funcțiile PRO pentru o lună.', renewBody: 'Continuă să folosești toate funcțiile PRO.',
    buyAction: 'Activează PRO', renewAction: 'Prelungește PRO', openWallet: 'Deschide portofelul meu',
  },
};

Object.assign(copy.ru, {
  signalsTitle: 'Автосигналы XAUUSD',
  signalsBody: 'ИИ-анализ рынка, автоматические сигналы по золоту (XAUUSD) и отчёты о результатах — в Gold Scalping. Telegram-бот присылает сигналы: решение о торговле остаётся за вами.',
  signalsBot: 'По желанию к этим же сигналам можно подключить Skalp_XAUUSD — бота автоторговли для cTrader. Установка в терминал или размещение на VPS оформляются отдельно; инструкции и актуальные условия — в канале.',
  signalsNote: 'Это отдельное подключение: синхронизация журнала DAYRIS не запускает автоторговлю. Сигналы не гарантируют прибыль; торговля может привести к потере капитала.',
  signalsAction: 'Канал и подключение автоторговли',
  signalsReceive: 'Получать сигналы в Telegram-боте',
  traderTitle: 'Два подключения. Один торговый журнал.',
  traderBody: 'Включите режим трейдера: сделки, PnL, кривая результата и аналитика отдельно от личных денег. Подключайте cTrader и MetaTrader 5 через отдельные меню.',
  traderPoints: ['Журнал сделок и аналитика PnL', 'Выбор торгового счёта на каждой площадке', 'Своя синхронизация и результат загрузки'],
  ctraderGuide: 'Прямое подключение: выберите счёт и загрузите сделки. В меню видно, сколько записей в журнале и что добавила последняя проверка.',
  mt5Guide: 'Подключение через бесплатный помощник Windows. Автообновление требует открытых MT5, помощника и DAYRIS в Chrome/Edge на ПК. На телефон сделки приходят через облачную синхронизацию DAYRIS.',
  openPlatforms: 'Открыть торговые площадки',
});
Object.assign(copy.en, {
  signalsTitle: 'XAUUSD automated signals',
  signalsBody: 'Gold Scalping provides AI market analysis, automated gold (XAUUSD) signals and result reports. The Telegram bot delivers signals; trading decisions remain yours.',
  signalsBot: 'Optionally connect Skalp_XAUUSD, an automated trading bot for cTrader, to the same signals. Terminal installation or VPS hosting is arranged separately. See the channel for instructions and current terms.',
  signalsNote: 'This is a separate connection: DAYRIS journal synchronization does not enable automated trading. Signals do not guarantee profits; trading can result in loss of capital.',
  signalsAction: 'Channel and automated trading setup',
  signalsReceive: 'Receive signals in the Telegram bot',
  traderTitle: 'Two connections. One trading journal.',
  traderBody: 'Enable Trader Mode for trades, PnL, your result curve and analytics, separate from personal money. Connect cTrader and MetaTrader 5 through dedicated menus.',
  traderPoints: ['Trade journal and PnL analytics', 'Choose a trading account per platform', 'Separate sync controls and import results'],
  ctraderGuide: 'Direct connection: choose an account and load trades. See journal entries and the result of your latest check.',
  mt5Guide: 'Connect through the free Windows companion. Auto-refresh requires MT5, the companion and DAYRIS open in desktop Chrome/Edge. Trades reach mobile through DAYRIS cloud sync.',
  openPlatforms: 'Open trading platforms',
});
Object.assign(copy.ro, {
  signalsTitle: 'Semnale automate XAUUSD',
  signalsBody: 'Gold Scalping oferă analiză AI a pieței, semnale automate pentru aur (XAUUSD) și rapoarte de rezultate. Botul Telegram trimite semnalele; decizia de tranzacționare îți aparține.',
  signalsBot: 'Opțional, conectează Skalp_XAUUSD, un bot de tranzacționare automată pentru cTrader, la aceleași semnale. Instalarea în terminal sau găzduirea pe VPS se stabilesc separat. Instrucțiunile și condițiile actuale sunt pe canal.',
  signalsNote: 'Este o conectare separată: sincronizarea jurnalului DAYRIS nu activează tranzacționarea automată. Semnalele nu garantează profit; tranzacționarea poate duce la pierderea capitalului.',
  signalsAction: 'Canal și conectare pentru trading automat',
  signalsReceive: 'Primește semnale în botul Telegram',
  traderTitle: 'Două conexiuni. Un jurnal de trading.',
  traderBody: 'Activează modul Trader pentru tranzacții, PnL, curba rezultatului și analiză, separat de banii personali. Conectează cTrader și MetaTrader 5 prin meniuri separate.',
  traderPoints: ['Jurnal de tranzacții și analiză PnL', 'Alegerea contului pentru fiecare platformă', 'Sincronizare și rezultate de import separate'],
  ctraderGuide: 'Conectare directă: alege contul și încarcă tranzacțiile. Vezi înregistrările din jurnal și rezultatul ultimei verificări.',
  mt5Guide: 'Conectare prin asistentul Windows gratuit. Actualizarea automată necesită MT5, asistentul și DAYRIS deschise în Chrome/Edge pe PC. Tranzacțiile ajung pe telefon prin cloud DAYRIS.',
  openPlatforms: 'Deschide platformele de trading',
});

export const XAUUSD_SIGNALS_URL = 'https://t.me/xauusd_scalp_signal';
export const XAUUSD_SIGNALS_BOT_URL = 'https://t.me/XauusdScalpSignal_bot';

export function getProOfferCopy(language) {
  const locale = String(language || 'ru').toLowerCase().split('-')[0];
  return copy[locale === 'md' ? 'ro' : locale] || copy.ru;
}
