export function plannerLanguage(language) {
  const code = String(language || '').toLowerCase();
  if (code.startsWith('zh')) return 'zh';
  if (code === 'en' || code.startsWith('en-')) return 'en';
  if (code === 'md' || code === 'ro' || code.startsWith('ro-')) return 'ro';
  return 'ru';
}

export const PLANNER_COPY = {
  zh: {
    locale:'zh-CN', badge:'个人计划', editBadge:'编辑计划', close:'关闭', steps:['事项','时间安排','完成'], headings:['计划什么？','何时提醒？','准备就绪'], descriptions:['选择常用事项，或创建自己的事项。','一次或定期，由你决定。','确认详情，其余交给 DAYRIS。'], templates:[['贷款','偿还贷款','expense'],['手机话费','手机充值','expense'],['房租','支付房租','expense'],['工资','工资','income']], custom:'自定义事项',customHint:'记录重要事项',title:'事项名称',placeholder:'例如，支付学费',addAmount:'添加金额',optional:'选填',amount:'金额',currency:'货币',expense:'支出',income:'收入',amountLater:'可以稍后填写金额',date:'事项日期',firstDate:'首次日期',time:'时间',localTime:'当地时间',repeat:'重复？',frequencies:['仅一次','每月','每周','每年'],monthly:day=>`每月 ${day} 日`,shortMonth:'较短月份在最后一天执行。',limit:'何时结束？',unlimited:'无限制',total:'事项次数',until:'结束日期',countSummary:count=>`共 ${count} 次`,untilSummary:date=>`截至 ${date}`,limitsHint:'首次事项计入次数。若同时设置两种限制，以先达到的为准。',notify:'提醒我',offsets:['事项发生时','提前一天','提前三天','提前一周'],notification:'通知',firstNotification:'首次通知',late:'首次事项已无法提前提醒，将在事项发生时通知。后续按所选规则提醒。',note:'计划立即显示在日历中，确认后才计入余额。',editNote:'更新提醒，已发送的通知不会重复。',change:'修改',noAmount:'无金额',back:'返回',details:'设置详情',review:'确认计划',createNow:'立即创建',saveNow:'保存',create:'创建提醒',save:'保存更改',saving:'正在保存…',requiredTitle:'请输入事项名称。',invalidAmount:'请输入大于或等于 0 的金额，或留空。',future:'请选择未来日期及有效时间。',invalidUntil:'结束日期不能早于首次事项。',invalidCount:'请选择 1 至 600 次。',failed:'无法保存，请重试。',push:'请在浏览器设置中允许通知后重试。',
  },
  ru: {
    locale: 'ru-RU', badge: 'Личный план', editBadge: 'Редактирование', close: 'Закрыть',
    steps: ['Событие', 'Расписание', 'Готово'],
    headings: ['Что запланируем?', 'Когда напомнить?', 'Всё готово к старту'],
    descriptions: ['Выберите знакомое или придумайте своё.', 'Один раз или регулярно — решаете вы.', 'Проверьте детали. Остальное — за DAYRIS.'],
    templates: [['Кредит', 'Платёж по кредиту', 'expense'], ['Мобильная связь', 'Пополнение мобильного', 'expense'], ['Аренда', 'Оплата аренды', 'expense'], ['Зарплата', 'Зарплата', 'income']],
    custom: 'Своё событие', customHint: 'Всё, что важно не забыть', title: 'Название события', placeholder: 'Например, оплатить обучение',
    addAmount: 'Добавить сумму', optional: 'Необязательно', amount: 'Сумма', currency: 'Валюта', expense: 'Расход', income: 'Доход', amountLater: 'Сумму можно добавить позже',
    date: 'Дата события', firstDate: 'Первый раз', time: 'Время', localTime: 'По местному времени',
    repeat: 'Повторять?', frequencies: ['Один раз', 'Каждый месяц', 'Каждую неделю', 'Каждый год'],
    monthly: (day) => `Каждый месяц, ${day} числа`, shortMonth: 'В коротком месяце — в последний день.',
    limit: 'Когда остановиться?', unlimited: 'Без ограничения', total: 'Количество событий', until: 'Дата окончания',
    countSummary: (count) => `Всего событий: ${count}`, untilSummary: (date) => `До ${date}`,
    limitsHint: 'Первое событие входит в счёт. Если выбраны оба ограничения, сработает то, которое наступит раньше.',
    notify: 'Напомнить', offsets: ['В момент события', 'За день', 'За 3 дня', 'За неделю'],
    notification: 'Уведомление', firstNotification: 'Первое уведомление',
    late: 'Для первого события напомнить заранее уже поздно — уведомим в момент события. Дальше — по вашему правилу.',
    note: 'План сразу появится в календаре. В баланс — только после вашего подтверждения.',
    editNote: 'Сохраним изменения в напоминании. Уже отправленные уведомления не повторятся.',
    change: 'Изменить', noAmount: 'Без суммы', back: 'Назад', details: 'Настроить детали', review: 'Всё верно?',
    createNow: 'Создать сейчас', saveNow: 'Сохранить', create: 'Создать напоминание', save: 'Сохранить изменения', saving: 'Сохраняем…',
    requiredTitle: 'Как назовём событие?', invalidAmount: 'Введите сумму от 0 или оставьте поле пустым.',
    future: 'Выберите будущий день и время события.', invalidUntil: 'Окончание не может быть раньше первого события.',
    invalidCount: 'Выберите количество от 1 до 600.', failed: 'Не удалось сохранить. Попробуйте ещё раз.',
    push: 'Разрешите уведомления в настройках браузера и попробуйте ещё раз.',
  },
  en: {
    locale: 'en-US', badge: 'Your personal plan', editBadge: 'Edit reminder', close: 'Close',
    steps: ['Event', 'Schedule', 'Ready'],
    headings: ['What’s the plan?', 'When should we remind you?', 'All set to go'],
    descriptions: ['Pick a familiar event or make it your own.', 'Just once or regularly — it’s up to you.', 'Check the details. DAYRIS takes it from here.'],
    templates: [['Loan payment', 'Loan payment', 'expense'], ['Mobile top-up', 'Mobile top-up', 'expense'], ['Rent', 'Rent payment', 'expense'], ['Salary', 'Salary', 'income']],
    custom: 'Your own event', customHint: 'Anything worth remembering', title: 'Event name', placeholder: 'For example, pay tuition',
    addAmount: 'Add an amount', optional: 'Optional', amount: 'Amount', currency: 'Currency', expense: 'Expense', income: 'Income', amountLater: 'You can add the amount later',
    date: 'Event date', firstDate: 'First occurrence', time: 'Time', localTime: 'Your local time',
    repeat: 'Repeat?', frequencies: ['Just once', 'Every month', 'Every week', 'Every year'],
    monthly: (day) => `Every month, on day ${day}`, shortMonth: 'In shorter months, on the last day.',
    limit: 'When should it stop?', unlimited: 'No limit', total: 'Number of events', until: 'End date',
    countSummary: (count) => `${count} events in total`, untilSummary: (date) => `Until ${date}`,
    limitsHint: 'The first event counts too. If you set both limits, the earlier one applies.',
    notify: 'Remind me', offsets: ['At event time', '1 day before', '3 days before', '1 week before'],
    notification: 'Notification', firstNotification: 'First notification',
    late: 'It’s too late for an early reminder for the first event. We’ll notify you at the event time, then follow your rule.',
    note: 'Your plan appears in the calendar right away. Your balance changes only after you confirm.',
    editNote: 'We’ll update this reminder. Notifications already sent won’t be repeated.',
    change: 'Edit', noAmount: 'No amount yet', back: 'Back', details: 'Set up details', review: 'Review plan',
    createNow: 'Create now', saveNow: 'Save', create: 'Create reminder', save: 'Save changes', saving: 'Saving…',
    requiredTitle: 'Give your event a name.', invalidAmount: 'Enter an amount of 0 or more, or leave it blank.',
    future: 'Choose a future day and a valid event time.', invalidUntil: 'The end date can’t be before the first event.',
    invalidCount: 'Choose a number from 1 to 600.', failed: 'Couldn’t save. Please try again.',
    push: 'Allow notifications in your browser settings and try again.',
  },
  ro: {
    locale: 'ro-RO', badge: 'Planul tău personal', editBadge: 'Editează mementoul', close: 'Închide',
    steps: ['Eveniment', 'Program', 'Gata'],
    headings: ['Ce planificăm?', 'Când îți amintim?', 'Totul e pregătit'],
    descriptions: ['Alege un eveniment sau creează unul propriu.', 'O singură dată sau regulat — tu decizi.', 'Verifică detaliile. De restul se ocupă DAYRIS.'],
    templates: [['Credit', 'Plata creditului', 'expense'], ['Telefon mobil', 'Reîncărcare mobil', 'expense'], ['Chirie', 'Plata chiriei', 'expense'], ['Salariu', 'Salariu', 'income']],
    custom: 'Eveniment propriu', customHint: 'Orice merită ținut minte', title: 'Numele evenimentului', placeholder: 'De exemplu, plata studiilor',
    addAmount: 'Adaugă suma', optional: 'Opțional', amount: 'Sumă', currency: 'Monedă', expense: 'Cheltuială', income: 'Venit', amountLater: 'Poți adăuga suma mai târziu',
    date: 'Data evenimentului', firstDate: 'Prima dată', time: 'Ora', localTime: 'Ora ta locală',
    repeat: 'Se repetă?', frequencies: ['O singură dată', 'În fiecare lună', 'Săptămânal', 'Anual'],
    monthly: (day) => `Lunar, în ziua de ${day}`, shortMonth: 'În lunile mai scurte — în ultima zi.',
    limit: 'Când se încheie?', unlimited: 'Fără limită', total: 'Număr de evenimente', until: 'Data de final',
    countSummary: (count) => `${count} evenimente în total`, untilSummary: (date) => `Până la ${date}`,
    limitsHint: 'Primul eveniment este inclus. Dacă alegi ambele limite, se aplică prima atinsă.',
    notify: 'Amintește-mi', offsets: ['La ora evenimentului', 'Cu o zi înainte', 'Cu 3 zile înainte', 'Cu o săptămână înainte'],
    notification: 'Notificare', firstNotification: 'Prima notificare',
    late: 'Este prea târziu pentru o notificare anticipată a primului eveniment. Te anunțăm la ora lui, apoi urmăm regula aleasă.',
    note: 'Planul apare imediat în calendar. Soldul se schimbă doar după confirmarea ta.',
    editNote: 'Actualizăm mementoul. Notificările deja trimise nu se repetă.',
    change: 'Editează', noAmount: 'Fără sumă', back: 'Înapoi', details: 'Alege detaliile', review: 'Verifică planul',
    createNow: 'Creează acum', saveNow: 'Salvează', create: 'Creează memento', save: 'Salvează modificările', saving: 'Se salvează…',
    requiredTitle: 'Cum numim evenimentul?', invalidAmount: 'Introdu o sumă de la 0 sau lasă câmpul gol.',
    future: 'Alege o zi viitoare și o oră validă.', invalidUntil: 'Finalul nu poate fi înaintea primului eveniment.',
    invalidCount: 'Alege un număr între 1 și 600.', failed: 'Nu s-a putut salva. Încearcă din nou.',
    push: 'Permite notificările în setările browserului și încearcă din nou.',
  },
};
