import React, { useMemo, useState } from 'react';
import { Plus, Pencil, Trash2, Wallet } from 'lucide-react';
import { CURRENCIES, getCurrencyMeta } from '../../shared/config/constants';

export default function WalletPanel({ isLight, currency, transactions, balanceByCurrency, loading, error, onSave, onDelete }) {
  const [form, setForm] = useState(null);
  const [busy, setBusy] = useState(false);
  const [filterCurrency, setFilterCurrency] = useState(currency || 'USD');
  const visible = useMemo(() => transactions.filter((item) => item.currency === filterCurrency), [transactions, filterCurrency]);
  const balance = balanceByCurrency[filterCurrency] || 0;
  const openNew = () => setForm({ dateKey: new Date().toISOString().slice(0, 10), time: '12:00', title: '', amount: '', kind: 'expense', currency: filterCurrency, comment: '' });
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { await onSave({ ...form, amount: Number(form.amount) }); setForm(null); } finally { setBusy(false); } };
  return <section className="flex-1 px-3 py-4 sm:px-8 sm:py-6"><div className="mx-auto max-w-3xl"><div className={`rounded-3xl border p-5 sm:p-7 ${isLight ? 'border-zinc-200 bg-white' : 'border-zinc-800 bg-zinc-900/50'}`}>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-amber-500"><Wallet className="h-5 w-5" /><span className="font-data text-[10px] uppercase tracking-[.2em]">Wallet</span></div><h2 className="mt-2 text-2xl font-semibold">Кошелёк</h2><p className="mt-1 text-xs text-zinc-500">Отдельный счёт, не входящий в PnL и торговую статистику.</p></div><button type="button" onClick={openNew} className="inline-flex items-center gap-2 rounded-xl bg-amber-400 px-3 py-2 text-sm font-semibold text-zinc-950"><Plus className="h-4 w-4" />Добавить</button></div>
    <div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs text-zinc-500">Текущий баланс · {filterCurrency}</p><p className={`mt-1 font-data text-3xl font-bold ${balance >= 0 ? 'text-emerald-500' : 'text-red-500'}`}>{balance >= 0 ? '+' : '−'}{getCurrencyMeta(filterCurrency).symbol}{Math.abs(balance).toFixed(2)}</p></div><select value={filterCurrency} onChange={(e) => setFilterCurrency(e.target.value)} className={`rounded-xl border px-3 py-2 text-sm ${isLight ? 'border-zinc-200 bg-white' : 'border-zinc-700 bg-zinc-900'}`}>{CURRENCIES.map((item) => <option key={item.code} value={item.code}>{item.code}</option>)}</select></div>
    {error && <p className="mt-4 rounded-xl bg-red-500/10 p-3 text-xs text-red-500">{error === 'WALLET_MIGRATION_REQUIRED' ? 'Кошелёк ещё не подключён к Supabase: нужно применить миграцию wallet_transactions.' : 'Не удалось синхронизировать кошелёк.'}</p>}
    {form && <form onSubmit={submit} className="mt-6 grid gap-3 rounded-2xl border border-zinc-700 p-4 sm:grid-cols-2"><input required placeholder="Название" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="rounded-xl border bg-transparent px-3 py-2 text-sm" /><input required type="number" min="0" step="0.01" placeholder="Сумма" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} className="rounded-xl border bg-transparent px-3 py-2 text-sm" /><input required type="date" value={form.dateKey} onChange={(e) => setForm({ ...form, dateKey: e.target.value })} className="rounded-xl border bg-transparent px-3 py-2 text-sm" /><select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })} className="rounded-xl border bg-transparent px-3 py-2 text-sm"><option value="expense">Расход</option><option value="income">Доход</option></select><textarea placeholder="Комментарий" value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} className="rounded-xl border bg-transparent px-3 py-2 text-sm sm:col-span-2" /><div className="flex gap-2 sm:col-span-2"><button disabled={busy} className="rounded-xl bg-amber-400 px-4 py-2 text-sm font-semibold text-zinc-950">{busy ? 'Сохраняю…' : 'Сохранить'}</button><button type="button" onClick={() => setForm(null)} className="rounded-xl px-4 py-2 text-sm text-zinc-500">Отмена</button></div></form>}
    <div className="mt-6 space-y-2">{loading && <p className="py-8 text-center text-sm text-zinc-500">Загрузка…</p>}{!loading && visible.length === 0 && <div className="rounded-2xl border border-dashed border-zinc-700 px-5 py-10 text-center"><Wallet className="mx-auto h-8 w-8 text-zinc-500" /><p className="mt-3 text-sm font-medium">В кошельке пока нет операций</p><p className="mt-1 text-xs text-zinc-500">Добавьте первый доход или расход.</p></div>}{visible.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-zinc-800 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.title}</p><p className="text-xs text-zinc-500">{item.dateKey}{item.comment ? ` · ${item.comment}` : ''}</p></div><span className={`font-data text-sm font-semibold ${item.kind === 'income' ? 'text-emerald-500' : 'text-red-500'}`}>{item.kind === 'income' ? '+' : '−'}{getCurrencyMeta(item.currency).symbol}{item.amount.toFixed(2)}</span><button type="button" aria-label="Редактировать" onClick={() => setForm(item)} className="p-2 text-zinc-500"><Pencil className="h-4 w-4" /></button><button type="button" aria-label="Удалить" onClick={() => onDelete(item.id)} className="p-2 text-zinc-500"><Trash2 className="h-4 w-4" /></button></div>)}</div>
  </div></div></section>;
}
