import React, { useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, Check, CreditCard, Plus, Trash2, Wallet } from 'lucide-react';
import { CURRENCIES, getCurrencyMeta } from '../../shared/config/constants';

const field = 'w-full rounded-xl border border-white/10 bg-white/[.045] px-3 py-3 text-sm text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-amber-400/70';

export default function WalletPanel({ isLight, currency, transactions, transfers = [], balanceByCurrency, loading, error, onSave, onDelete, onTransfer, onClearHistory = async () => {} }) {
  const [step, setStep] = useState(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [code, setCode] = useState(currency || 'USD');
  const [data, setData] = useState({ kind: 'expense', account: 'wallet', amount: '', title: '', dateKey: new Date().toISOString().slice(0, 10), comment: '' });
  const rows = useMemo(() => transactions.filter((x) => x.currency === code), [transactions, code]);
  const activities = useMemo(() => [...rows.map((x) => ({ ...x, type: x.kind, date: x.dateKey })), ...transfers.filter((x) => x.currency === code).map((x) => ({ ...x, id: `transfer-${x.id}`, type: x.to_account === 'wallet' ? 'topup' : 'withdraw', date: x.date_key, amount: Number(x.amount) || 0 }))].sort((a, b) => String(b.date).localeCompare(String(a.date))), [rows, transfers, code]);
  const balance = balanceByCurrency[code] || 0;
  const symbol = getCurrencyMeta(code).symbol;
  const start = (kind) => { setMessage(''); setData((x) => ({ ...x, kind, account: kind === 'transfer' ? 'main-to-wallet' : 'wallet' })); setStep(kind); };
  const submit = async (event) => { event.preventDefault(); setBusy(true); setMessage(''); try { if (step === 'transfer') { const [fromAccount, toAccount] = data.account.split('-to-'); await onTransfer({ amount: Number(data.amount), currency: code, fromAccount, toAccount, dateKey: data.dateKey, comment: data.comment }); } else { await onSave({ dateKey: data.dateKey, time: '12:00', title: data.title, amount: Number(data.amount), kind: data.kind, currency: code, comment: data.comment }); } setStep(null); } catch (err) { setMessage(err.message || 'Не удалось сохранить операцию.'); } finally { setBusy(false); } };
  return <section className={`min-h-0 flex-1 overflow-y-auto px-3 py-5 sm:px-8 sm:py-8 ${isLight ? 'bg-[#f5f6f8]' : 'bg-[#090a0d]'}`}><div className="mx-auto max-w-4xl">
    <header className="mb-6"><p className="font-data text-[10px] uppercase tracking-[.28em] text-amber-500">Private finance · отдельный счёт</p><h2 className="mt-2 text-3xl font-semibold text-white">Кошелёк</h2><p className="mt-1 text-sm text-zinc-500">Личные деньги отдельно от сделок и торгового PnL.</p></header>
    <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/[.08] bg-white/[.03] p-5"><p className="text-xs text-zinc-500">Основной счёт</p><p className="mt-3 font-data text-2xl text-zinc-300">—</p><p className="mt-1 text-xs text-zinc-600">Обычные финансовые записи</p></div><div className="rounded-2xl border border-amber-400/25 bg-gradient-to-br from-amber-400/[.12] to-white/[.02] p-5"><div className="flex items-center justify-between"><p className="text-xs text-amber-300">Кошелёк · PRO</p><select value={code} onChange={(e) => setCode(e.target.value)} className="rounded-lg bg-black/30 px-2 py-1 text-xs text-zinc-100">{CURRENCIES.map((x) => <option key={x.code} value={x.code}>{x.code} · {x.symbol}</option>)}</select></div><p className="mt-3 font-data text-2xl text-emerald-400">{loading ? '—' : `${symbol}${Math.abs(balance).toFixed(2)}`}</p><p className="mt-1 text-xs text-zinc-500">Отдельный баланс кошелька</p></div></div>
    <button type="button" onClick={() => setStep('choose')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-amber-400 px-5 py-4 font-semibold text-zinc-950"><Plus className="h-5 w-5" />Добавить операцию</button>
    {step && <div className="mt-5 rounded-3xl border border-amber-400/20 bg-[#121317] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-amber-400">{step === 'choose' ? 'Шаг 1' : 'Новая операция'}</p><h3 className="mt-1 text-lg font-semibold text-white">{step === 'choose' ? 'Что произошло?' : step === 'transfer' ? 'Перемещение денег' : step === 'income' ? 'Получил деньги' : 'Потратил деньги'}</h3></div><button type="button" onClick={() => setStep(null)} className="text-sm text-zinc-500">Закрыть</button></div>{step === 'choose' ? <div className="mt-5 grid gap-2 sm:grid-cols-3"><button type="button" onClick={() => start('income')} className="rounded-2xl bg-emerald-400/10 p-4 text-left text-emerald-300">Доход<br /><span className="text-xs text-zinc-500">Зачислить деньги</span></button><button type="button" onClick={() => start('expense')} className="rounded-2xl bg-red-400/10 p-4 text-left text-red-300">Расход<br /><span className="text-xs text-zinc-500">Списать деньги</span></button><button type="button" onClick={() => start('transfer')} className="rounded-2xl bg-white/5 p-4 text-left text-zinc-200">Перевод<br /><span className="text-xs text-zinc-500">Между счетами</span></button></div> : <form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-2"><select value={data.account} onChange={(e) => setData({ ...data, account: e.target.value })} className={field}>{step === 'transfer' ? <><option value="main-to-wallet">Основной счёт → Кошелёк</option><option value="wallet-to-main">Кошелёк → Основной счёт</option></> : <><option value="wallet">Кошелёк</option><option value="main">Основной счёт</option></>}</select><input required type="number" min="0.01" step="0.01" placeholder="Сумма" value={data.amount} onChange={(e) => setData({ ...data, amount: e.target.value })} className={field} />{step !== 'transfer' && <input required placeholder="Название" value={data.title} onChange={(e) => setData({ ...data, title: e.target.value })} className={field} />}<input required type="date" value={data.dateKey} onChange={(e) => setData({ ...data, dateKey: e.target.value })} className={field} /><textarea placeholder="Комментарий" value={data.comment} onChange={(e) => setData({ ...data, comment: e.target.value })} className={`${field} sm:col-span-2`} />{message && <p className="text-xs text-red-400 sm:col-span-2">{message}</p>}<button disabled={busy} className="rounded-xl bg-amber-400 px-4 py-3 font-semibold text-zinc-950 sm:col-span-2">{busy ? 'Сохраняю…' : <><Check className="mr-2 inline h-4 w-4" />Сохранить</>}</button></form>}</div>}
    <div className="mt-8 flex items-center gap-2"><CreditCard className="h-4 w-4 text-amber-500" /><h3 className="text-sm font-semibold text-zinc-200">История операций</h3><span className="text-xs text-zinc-500">· {activities.length}</span></div><div className="mt-3 space-y-2">{activities.map((item) => { const positive = item.type === 'income' || item.type === 'topup'; const transfer = item.type === 'topup' || item.type === 'withdraw'; return <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${positive ? 'bg-emerald-400/10 text-emerald-400' : 'bg-red-400/10 text-red-400'}`}>{transfer ? <ArrowLeftRight className="h-4 w-4" /> : positive ? <ArrowDownLeft className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span><div className="flex-1"><p className="text-sm font-semibold text-zinc-200">{transfer ? item.type === 'topup' ? 'Основной счёт → Кошелёк' : 'Кошелёк → Основной счёт' : item.title}</p><p className="text-xs text-zinc-500">{item.date}</p></div><span className={`font-data text-sm ${positive ? 'text-emerald-400' : 'text-red-400'}`}>{positive ? '+' : '−'}{getCurrencyMeta(item.currency).symbol}{item.amount.toFixed(2)}</span>{!transfer && <button type="button" onClick={() => onDelete(item.id)} className="p-2 text-zinc-600"><Trash2 className="h-4 w-4" /></button>}</div>; })}</div>{activities.length > 0 && <button type="button" onClick={async () => { if (window.confirm('Удалить всю историю кошелька и переводы?')) await onClearHistory(); }} className="mt-4 text-xs text-zinc-500 hover:text-red-400">Очистить историю</button>}
  </div></section>;
}
