import React, { useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, CalendarDays, Check, ChevronDown, CreditCard, Pencil, Plus, Trash2, Wallet } from 'lucide-react';
import { CURRENCIES, getCurrencyMeta } from '../../shared/config/constants';

const field = 'w-full rounded-xl border border-white/10 bg-white/[.045] px-3.5 py-3 text-sm text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-amber-400/70';

export default function WalletPanel({ isLight, currency, transactions, balanceByCurrency, loading, error, onSave, onDelete, onTransfer }) {
  const [form, setForm] = useState(null); const [transferForm, setTransferForm] = useState(null); const [busy, setBusy] = useState(false); const [code, setCode] = useState(currency || 'USD');
  const rows = useMemo(() => transactions.filter((item) => item.currency === code), [transactions, code]);
  const balance = balanceByCurrency[code] || 0; const symbol = getCurrencyMeta(code).symbol;
  const income = rows.filter((x) => x.kind === 'income').reduce((s, x) => s + x.amount, 0);
  const expenses = rows.filter((x) => x.kind === 'expense').reduce((s, x) => s + x.amount, 0);
  const openNew = () => setForm({ dateKey: new Date().toISOString().slice(0, 10), time: '12:00', title: '', amount: '', kind: 'expense', currency: code, comment: '' });
  const submit = async (e) => { e.preventDefault(); setBusy(true); try { await onSave({ ...form, amount: Number(form.amount) }); setForm(null); } finally { setBusy(false); } };
  return <section className={`min-h-0 flex-1 overflow-y-auto px-3 py-5 sm:px-8 sm:py-8 ${isLight ? 'bg-[#f5f6f8]' : 'bg-[#090a0d]'}`}><div className="mx-auto max-w-4xl">
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="font-data text-[10px] uppercase tracking-[.28em] text-amber-500">Private finance</p><h2 className={`mt-2 text-3xl font-semibold tracking-tight ${isLight ? 'text-zinc-900' : 'text-white'}`}>Кошелёк</h2><p className="mt-1 text-sm text-zinc-500">Личные деньги отдельно от торгового счёта</p></div><div className="flex gap-2"><button type="button" onClick={() => setTransferForm({ amount: '', dateKey: new Date().toISOString().slice(0, 10), fromAccount: 'main', toAccount: 'wallet', comment: '' })} className="rounded-xl border border-amber-400/30 px-3 py-3 text-xs font-semibold text-amber-400">Пополнить</button><button type="button" onClick={() => setTransferForm({ amount: '', dateKey: new Date().toISOString().slice(0, 10), fromAccount: 'wallet', toAccount: 'main', comment: '' })} className="rounded-xl border border-white/10 px-3 py-3 text-xs font-semibold text-zinc-400">Вывести</button><button type="button" onClick={openNew} className="inline-flex items-center gap-2 rounded-xl bg-amber-400 px-4 py-3 text-sm font-semibold text-zinc-950 shadow-[0_8px_24px_rgba(251,191,36,.18)]"><Plus className="h-4 w-4" />Новая запись</button></div></div>
    <div className="relative overflow-hidden rounded-[28px] border border-amber-400/20 bg-gradient-to-br from-[#1c1a14] via-[#111216] to-[#0b0c0f] p-5 shadow-[0_24px_80px_rgba(0,0,0,.28)] sm:p-7"><div className="pointer-events-none absolute -right-16 -top-24 h-64 w-64 rounded-full bg-amber-400/10 blur-3xl" /><div className="relative flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-amber-300"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-amber-300/20 bg-amber-300/10"><Wallet className="h-4 w-4" /></span><span className="text-xs font-medium uppercase tracking-[.2em]">Wallet account</span></div><p className="mt-7 text-xs text-zinc-500">Доступный баланс</p><p className="mt-1 font-data text-4xl font-semibold tracking-tight text-white sm:text-5xl">{symbol}{Math.abs(balance).toLocaleString('ru-RU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p><p className={`mt-2 text-xs ${balance >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>{balance >= 0 ? 'Положительный баланс' : 'Отрицательный баланс'}</p></div><div className="relative"><select value={code} onChange={(e) => setCode(e.target.value)} className="wallet-currency-select appearance-none rounded-xl border border-white/10 bg-[#17181d] py-2.5 pl-3 pr-9 text-xs font-semibold text-zinc-100 outline-none focus:border-amber-400/70" style={{ colorScheme: 'dark' }}><option value="USD" style={{ backgroundColor: '#111216', color: '#f4f4f5' }}>USD · $</option>{CURRENCIES.filter((x) => x.code !== 'USD').map((x) => <option key={x.code} value={x.code} style={{ backgroundColor: '#111216', color: '#f4f4f5' }}>{x.code} · {x.symbol}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-3.5 w-3.5 text-zinc-400" /></div></div><div className="relative mt-8 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.07] p-3"><div className="flex items-center gap-2 text-xs text-emerald-300"><ArrowDownLeft className="h-4 w-4" />Доходы</div><p className="mt-2 font-data text-lg text-emerald-300">+{symbol}{income.toFixed(2)}</p></div><div className="rounded-2xl border border-red-400/15 bg-red-400/[.06] p-3"><div className="flex items-center gap-2 text-xs text-red-300"><ArrowUpRight className="h-4 w-4" />Расходы</div><p className="mt-2 font-data text-lg text-red-300">−{symbol}{expenses.toFixed(2)}</p></div></div></div>
    {error && <div className="mt-4 rounded-2xl border border-red-400/20 bg-red-400/[.06] p-4 text-xs text-red-300">{error === 'WALLET_MIGRATION_REQUIRED' ? 'Синхронизация ещё не подключена. Примените миграцию wallet_transactions в Supabase.' : 'Не удалось синхронизировать кошелёк.'}</div>}
    {transferForm && <form onSubmit={async (e) => { e.preventDefault(); setBusy(true); try { await onTransfer({ ...transferForm, amount: Number(transferForm.amount), currency: code }); setTransferForm(null); } finally { setBusy(false); } }} className="mt-5 rounded-[24px] border border-amber-400/20 bg-[#121317] p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-amber-400">Перевод между счетами</p><h3 className="mt-1 text-lg font-semibold text-white">{transferForm.fromAccount === 'main' ? 'Пополнить кошелёк' : 'Перевести на основной счёт'}</h3></div><button type="button" onClick={() => setTransferForm(null)} className="text-sm text-zinc-500">Отмена</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required type="number" min="0.01" step="0.01" placeholder="Сумма" value={transferForm.amount} onChange={(e) => setTransferForm({ ...transferForm, amount: e.target.value })} className={field} /><input required type="date" value={transferForm.dateKey} onChange={(e) => setTransferForm({ ...transferForm, dateKey: e.target.value })} className={field} /><input placeholder="Комментарий" value={transferForm.comment} onChange={(e) => setTransferForm({ ...transferForm, comment: e.target.value })} className={`${field} sm:col-span-2`} /></div><button disabled={busy} className="mt-4 w-full rounded-xl bg-amber-400 px-4 py-3 text-sm font-semibold text-zinc-950">{busy ? 'Сохраняю…' : 'Подтвердить перевод'}</button></form>}
    {form && <form onSubmit={submit} className="mt-5 rounded-[24px] border border-amber-400/20 bg-[#121317] p-5 shadow-xl sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-amber-400">{form.id ? 'Редактирование' : 'Новая операция'}</p><h3 className="mt-1 text-lg font-semibold text-white">Добавить в кошелёк</h3></div><button type="button" onClick={() => setForm(null)} className="text-sm text-zinc-500">Отмена</button></div><div className="mb-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => setForm({ ...form, kind: 'income' })} className={`rounded-xl px-3 py-3 text-sm font-semibold ${form.kind === 'income' ? 'bg-emerald-400 text-zinc-950' : 'bg-white/5 text-zinc-400'}`}>Доход</button><button type="button" onClick={() => setForm({ ...form, kind: 'expense' })} className={`rounded-xl px-3 py-3 text-sm font-semibold ${form.kind === 'expense' ? 'bg-red-400 text-zinc-950' : 'bg-white/5 text-zinc-400'}`}>Расход</button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-zinc-500">Название<input required placeholder="Например, зарплата или продукты" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className={`${field} mt-1.5`} /></label><label className="text-xs text-zinc-500">Сумма<input required type="number" min="0" step="0.01" placeholder="0.00" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} className={`${field} mt-1.5`} /></label><label className="text-xs text-zinc-500">Дата<div className="relative mt-1.5"><CalendarDays className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-zinc-600" /><input required type="date" value={form.dateKey} onChange={(e) => setForm({ ...form, dateKey: e.target.value })} className={`${field} pl-10`} /></div></label><label className="text-xs text-zinc-500">Валюта<select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })} className={`${field} mt-1.5`}>{CURRENCIES.map((x) => <option key={x.code} value={x.code}>{x.code}</option>)}</select></label><label className="text-xs text-zinc-500 sm:col-span-2">Комментарий<textarea placeholder="Необязательно" value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} className={`${field} mt-1.5 min-h-20 resize-y`} /></label></div><button disabled={busy} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-amber-400 px-4 py-3 text-sm font-semibold text-zinc-950">{busy ? 'Сохраняю…' : <><Check className="h-4 w-4" />Сохранить операцию</>}</button></form>}
    <div className="mt-7 flex items-center gap-2"><CreditCard className="h-4 w-4 text-amber-500" /><h3 className={`text-sm font-semibold ${isLight ? 'text-zinc-800' : 'text-zinc-200'}`}>История операций</h3><span className="text-xs text-zinc-500">· {rows.length}</span></div><div className="mt-3 space-y-2">{loading && <p className="py-10 text-center text-sm text-zinc-500">Загружаем историю…</p>}{!loading && rows.length === 0 && <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center"><Wallet className="mx-auto h-8 w-8 text-zinc-600" /><p className="mt-3 text-sm font-semibold">История пока пуста</p><p className="mt-1 text-xs text-zinc-500">Добавьте первую операцию — доход или расход.</p></div>}{rows.map((item) => <div key={item.id} className="group flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-3.5 transition hover:border-amber-400/30"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.kind === 'income' ? 'bg-emerald-400/10 text-emerald-400' : 'bg-red-400/10 text-red-400'}`}>{item.kind === 'income' ? <ArrowDownLeft className="h-5 w-5" /> : <ArrowUpRight className="h-5 w-5" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.title}</p><p className="text-xs text-zinc-500">{item.dateKey}{item.comment ? ` · ${item.comment}` : ''}</p></div><span className={`font-data text-sm font-semibold ${item.kind === 'income' ? 'text-emerald-500' : 'text-red-500'}`}>{item.kind === 'income' ? '+' : '−'}{getCurrencyMeta(item.currency).symbol}{item.amount.toFixed(2)}</span><button type="button" aria-label="Редактировать" onClick={() => setForm(item)} className="rounded-lg p-2 text-zinc-600 hover:bg-white/10 hover:text-zinc-200"><Pencil className="h-4 w-4" /></button><button type="button" aria-label="Удалить" onClick={() => onDelete(item.id)} className="rounded-lg p-2 text-zinc-600 hover:bg-red-400/10 hover:text-red-400"><Trash2 className="h-4 w-4" /></button></div>)}</div>
  </div></section>;
}
